Repository codeit-team3/FE, pull requests merged in 2024-12, with the labels that each got.

#65 💄[Design] rootlayout 상단 padding 추가
  src/app/layout.tsx
Labels: 🎨 Design, D-0

#50 ✅[Test] 드롭다운 컴포넌트 storybook test코드 작성
  src/components/drop-down/DropDown.tsx
  src/components/drop-down/DroptDown.stories.tsx
Labels: ✅ Test, D-1

#53 📦[Chore] ci 작업 범위 및 메시지 수정
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
Labels: ⚙️ Chore, ♻️ Refactor, D-1

#49 ✨[Feat] WrittenReview, RatingDisplay 컴포넌트 생성 #38
  public/icons/RatingIcon.tsx
  public/icons/index.ts
  src/components/button2/Button2.stories.ts
  src/components/button2/Button2.tsx
  src/components/rating-display/RatingDisplay.stories.tsx
  src/components/rating-display/RatingDisplay.tsx
  src/components/written-review/WrittenReview.stories.tsx
  src/components/written-review/WrittenReview.test.tsx
  src/components/written-review/WrittenReview.tsx
Labels: ✅ Test, D-2, ✨ Feature

#71 📦[Chore] 줄 바꿈 스타일(LF) 통일 .gitattributes 파일 추가 #70
  .gitattributes
Labels: ⚙️ Chore, D-0

#67 💄[Design] DropDown UI 구현
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
  package-lock.json
  package.json
  public/icons/IcFiltering.tsx
  public/icons/IcSorting.tsx
  public/icons/RatingIcon.tsx
  public/icons/index.ts
  public/images/profile.png
  src/app/bookclub/page.tsx
  src/app/layout.tsx
  src/components/button/Button.stories.ts
  src/components/button/Button.test.tsx
  src/components/button/Button.tsx
  src/components/button2/Button2.stories.ts
  src/components/button2/Button2.tsx
  src/components/drop-down/DropDown.test.tsx
  src/components/drop-down/DropDown.tsx
  src/components/drop-down/DroptDown.stories.tsx
  src/components/rating-display/RatingDisplay.stories.tsx
  src/components/rating-display/RatingDisplay.tsx
  src/components/sorting-button/SortingButton.stories.tsx
  src/components/sorting-button/SortingButton.test.tsx
  src/components/sorting-button/SortingButton.tsx
  src/components/written-review/WrittenReview.stories.tsx
  src/components/written-review/WrittenReview.test.tsx
  src/components/written-review/WrittenReview.tsx
  tailwind.config.ts
Labels: 🎨 Design, D-1

#76 ✨[Feat] Color system 및 breakpoint, storybook preview 적용
  .storybook/preview.ts
  tailwind.config.ts
Labels: 🎨 Design, D-0, ✨ Feature

#69 ✨[Feat] Avatar, AvatarGroup 컴포넌트 구현
  next.config.ts
  src/components/avatar-group/AvatarGroup.stories.tsx
  src/components/avatar-group/AvatarGroup.test.tsx
  src/components/avatar-group/AvatarGroup.tsx
  src/components/avatar/Avatar.stories.tsx
  src/components/avatar/Avatar.test.tsx
  src/components/avatar/Avatar.tsx
  src/constants/avatar.ts
  src/constants/index.ts
Labels: ✅ Test, D-1, ✨ Feature

#42 ✨[Feat] CardList 컴포넌트 개발
  public/icons/HeartIcon.tsx
  public/icons/RightArrow.tsx
  public/icons/WaveIcon.tsx
  public/icons/index.ts
  src/components/card/Card.stories.tsx
  src/components/card/Card.test.tsx
  src/components/card/Card.tsx
  src/components/participant-counter/ParticipantCounter.tsx
  src/components/text-chip/TextChip.stories.tsx
  src/components/text-chip/TextChip.test.tsx
  src/components/text-chip/TextChip.tsx
Labels: ⚙️ Chore, ✅ Test, ✨ Feature

#44 ✨[Feat] 페이지별 권한에 따른 접근 처리 기능 구현 #43
  src/app/login/page.tsx
  src/features/auth/container/login-form/LoginForm.test.tsx
  src/features/auth/container/login-form/LoginForm.tsx
  src/middleware.ts
Labels: ✨ Feature

#97 ♻️ [Refactor] 피그마 디자인 시스템 컬러 명명 변경
  tailwind.config.ts
Labels: ♻️ Refactor, 🎨 Design, D-0

#45 ✨[Feat] 로그인 기능 구현 #34
  .eslintrc.json
  package-lock.json
  package.json
  public/icons/index.ts
  public/icons/visibility_off.tsx
  public/icons/visibility_on.tsx
  src/api/axios.ts
  src/app/login/page.tsx
  src/components/header/HeaderBar.tsx
  src/features/auth/api/auth.ts
  src/features/auth/api/index.ts
  src/features/auth/components/form-field/FormField.stories.tsx
  src/features/auth/components/form-field/FormField.test.tsx
  src/features/auth/components/form-field/FormField.tsx
  src/features/auth/components/index.ts
  src/features/auth/components/submit-button/SubmitButton.stories.tsx
  src/features/auth/components/submit-button/SubmitButton.test.tsx
  src/features/auth/components/submit-button/SubmitButton.tsx
  src/features/auth/constants/messages.ts
  src/features/auth/container/index.ts
  src/features/auth/container/login-form/LoginForm.stories.tsx
  src/features/auth/container/login-form/LoginForm.test.tsx
  src/features/auth/container/login-form/LoginForm.tsx
  src/features/auth/hooks/index.ts
  src/features/auth/hooks/useLoginSubmit.ts
  src/features/auth/hooks/usePasswordVisibility.ts
  src/features/auth/types/index.ts
  src/features/auth/types/loginFormSchema.ts
  src/features/auth/utils/cookies.ts
  src/lib/utils/apiClient.ts
  src/middleware.ts
  src/store/authStore.ts
  src/store/index.ts
Labels: ✨ Feature

#85 ♻️ [Refactor] chip 컴포넌트 리팩토링 #80
  src/components/card/Card.tsx
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.test.tsx
  src/components/chip/Chip.tsx
  src/components/text-chip/TextChip.stories.tsx
  src/components/text-chip/TextChip.test.tsx
  src/components/text-chip/TextChip.tsx
  tailwind.config.ts
Labels: ♻️ Refactor, 🎨 Design, ✅ Test, D-2

#101 🐛[Fix] LoginForm storybook 에러 해결
  src/features/auth/container/login-form/LoginForm.stories.tsx
Labels: 🐛 Bug, D-0

#90 💄[Design] 헤더 네비게이션 바 디자인 색상 변경
  src/components/header/HeaderBar.test.tsx
  src/components/header/HeaderBar.tsx
  src/components/header/NavButton.tsx
  src/constants/index.ts
  src/constants/navigation.ts
Labels: ♻️ Refactor, 🎨 Design, D-2

#93 ♻️[Refactor] common DropDown UI 리팩토링 #51 #84
  .eslintrc.json
  package-lock.json
  package.json
  public/icons/IcDropDown.tsx
  public/icons/index.ts
  public/icons/visibility_off.tsx
  public/icons/visibility_on.tsx
  src/api/axios.ts
  src/app/login/page.tsx
  src/components/drop-down/DropDown.test.tsx
  src/components/drop-down/DropDown.tsx
  src/components/drop-down/DroptDown.stories.tsx
  src/components/header/HeaderBar.tsx
  src/components/sorting-button/SortingButton.stories.tsx
  src/components/sorting-button/SortingButton.tsx
  src/features/auth/api/auth.ts
  src/features/auth/api/index.ts
  src/features/auth/components/form-field/FormField.stories.tsx
  src/features/auth/components/form-field/FormField.test.tsx
  src/features/auth/components/form-field/FormField.tsx
  src/features/auth/components/index.ts
  src/features/auth/components/submit-button/SubmitButton.stories.tsx
  src/features/auth/components/submit-button/SubmitButton.test.tsx
  src/features/auth/components/submit-button/SubmitButton.tsx
  src/features/auth/constants/messages.ts
  src/features/auth/container/index.ts
  src/features/auth/container/login-form/LoginForm.stories.tsx
  src/features/auth/container/login-form/LoginForm.test.tsx
  src/features/auth/container/login-form/LoginForm.tsx
  src/features/auth/hooks/index.ts
  src/features/auth/hooks/useLoginSubmit.ts
  src/features/auth/hooks/usePasswordVisibility.ts
  src/features/auth/types/index.ts
  src/features/auth/types/loginFormSchema.ts
  src/features/auth/utils/cookies.ts
  src/lib/utils/apiClient.ts
  src/middleware.ts
  src/store/authStore.ts
  src/store/index.ts
Labels: ♻️ Refactor, 🎨 Design, D-2

#108 ✨[Feat] Dropdown 컴포넌트 onclick 이벤트 구현
  src/components/drop-down/DropDown.stories.tsx
  src/components/drop-down/DropDown.test.tsx
  src/components/drop-down/DropDown.tsx
  src/components/drop-down/DroptDown.stories.tsx
  src/components/drop-down/hooks/useDropDownClose.ts
  src/components/sorting-button/SortingButton.stories.tsx
  src/components/sorting-button/SortingButton.tsx
  src/constants/dropdown.ts
  src/constants/index.ts
Labels: ✅ Test, ✨ Feature

#104 ✨[Feat] FilterCheckbox 컴포넌트 구현 #73
  src/components/filter-checkbox/FilterCheckbox.stories.tsx
  src/components/filter-checkbox/FilterCheckbox.test.tsx
  src/components/filter-checkbox/FilterCheckbox.tsx
Labels: 🎨 Design, ✅ Test, ✨ Feature

#109 ✨[Feat] common dropdown 구현 #47
  public/icons/IcDropDown.tsx
  public/icons/IcFiltering.tsx
  public/icons/IcSorting.tsx
  public/icons/index.ts
  public/images/profile.png
  src/components/drop-down/DropDown.stories.tsx
  src/components/drop-down/DropDown.test.tsx
  src/components/drop-down/DropDown.tsx
  src/components/drop-down/hooks/useDropDownClose.ts
  src/constants/dropdown.ts
  src/constants/index.ts
Labels: 🎨 Design, ✅ Test, ✨ Feature

#111 ✨[Feat] Tab 컴포넌트 구현 #107
  src/components/tab/Tab.stories.tsx
  src/components/tab/Tab.test.tsx
  src/components/tab/Tab.tsx
  src/constants/index.ts
  src/constants/tabs.ts
Labels: ✅ Test, ✨ Feature

#110 ♻️ [Refactor] common Button UI 리팩토링 #99
  src/components/button/Button.stories.ts
  src/components/button/Button.stories.tsx
  src/components/button/Button.test.tsx
  src/components/button/Button.tsx
  src/constants/button.ts
  src/constants/index.ts
Labels: ♻️ Refactor, D-1

#112 ♻️ [Refactor] Card Component 리팩토링
  public/icons/HeartIcon.tsx
  public/icons/HostIcon.tsx
  public/icons/IcCheck.tsx
  public/icons/LocationIcon.tsx
  public/icons/index.ts
  src/components/avatar-group/AvatarGroup.tsx
  src/components/avatar/Avatar.tsx
  src/components/card/Card.stories.tsx
  src/components/card/Card.test.tsx
  src/components/card/Card.tsx
  src/components/card/full-card/FullCard.stories.tsx
  src/components/card/full-card/FullCard.tsx
  src/components/card/mock/mock.ts
  src/components/card/simple-card/SimpleCard.stories.tsx
  src/components/card/simple-card/SimpleCard.tsx
  src/components/card/types/actions.ts
  src/components/card/types/base.ts
  src/components/card/types/components.ts
  src/components/card/types/index.ts
  src/components/card/types/meeting.ts
  src/components/card/types/models.ts
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.test.tsx
  src/components/chip/Chip.tsx
  src/components/confirmed-label/ConfirmedLabel.stories.tsx
  src/components/confirmed-label/ConfirmedLabel.test.tsx
  src/components/confirmed-label/ConfirmedLabel.tsx
  src/components/filter-checkbox/FilterCheckbox.tsx
  src/components/participant-counter/ParticipantCounter.stories.tsx
  src/components/participant-counter/ParticipantCounter.test.tsx
  src/components/participant-counter/ParticipantCounter.tsx
  src/components/progress-bar/ProgressBar.stories.tsx
  src/components/progress-bar/ProgressBar.test.tsx
  src/components/progress-bar/ProgressBar.tsx
  src/components/text-chip/TextChip.stories.tsx
  src/components/text-chip/TextChip.test.tsx
  src/components/text-chip/TextChip.tsx
  src/constants/avatar.ts
Labels: ♻️ Refactor, D-1, ✨ Feature

#121 ✨[Feat] 검색창 구현 #120
  public/icons/SearchIcon.tsx
  src/components/search-box/SearchBox.stories.tsx
  src/components/search-box/SearchBox.test.tsx
  src/components/search-box/SearchBox.tsx
Labels: 🎨 Design, ✅ Test, ✨ Feature

#118 ✨[Feat] 헤더 바에 있는 유저 버튼 드롭다운 버튼으로 변경 #103
  next.config.ts
  src/components/header/HeaderBar.test.tsx
  src/components/header/HeaderBar.tsx
Labels: ✨ Feature

#127 ♻️[Refactor] 로그인 버튼 공용 컴포넌트 버튼으로 변경 #124
  src/features/auth/components/submit-button/SubmitButton.stories.tsx
  src/features/auth/components/submit-button/SubmitButton.test.tsx
  src/features/auth/components/submit-button/SubmitButton.tsx
  src/features/auth/container/login-form/LoginForm.tsx
Labels: ♻️ Refactor

#122 ✨ [Feature] 모임 만들기 페이지 UI
  src/app/bookclub/create/page.tsx
  src/features/club-create/components/CreateClubFormField.tsx
  src/features/club-create/components/InputField.tsx
  src/features/club-create/components/RadioButtonGroup.tsx
  src/features/club-create/components/index.ts
  src/features/club-create/types/bookClubSchema.ts
  src/features/club-create/types/index.ts
Labels: 🎨 Design, ✨ Feature

#117 ✨[Feat] Common SortingButton 구현 #94
  public/icons/IcSorting.tsx
  src/components/sorting-button/SortingButton.stories.tsx
  src/components/sorting-button/SortingButton.test.tsx
  src/components/sorting-button/SortingButton.tsx
Labels: 🎨 Design, ✅ Test, D-1, ✨ Feature

#133 ♻️[Refactor] feature common popup #10
  package-lock.json
  public/icons/IcClose.tsx
  public/icons/index.ts
  src/components/pop-up/PopUp.stories.tsx
  src/components/pop-up/PopUp.test.tsx
  src/components/pop-up/PopUp.tsx
Labels: ♻️ Refactor, 🎨 Design, D-1, ✨ Feature

#130 ♻️ [Refactor] Compound Pattern 적용하여 WrittenReview 컴포넌트 구조 개선 #100
  public/icons/RatingIcon.tsx
  src/components/written-review/WrittenReview.stories.tsx
  src/components/written-review/WrittenReview.test.tsx
  src/components/written-review/WrittenReview.tsx
  src/components/written-review/types/writtenReview.ts
Labels: ♻️ Refactor, 🎨 Design, D-1

#136 💄[Design] Sub_Tab 디자인 변경
  src/components/button/Button.tsx
  src/components/tab/Tab.test.tsx
  src/components/tab/Tab.tsx
  src/constants/button.ts
Labels: ♻️ Refactor, 🎨 Design

#138 ♻️[Refactor] 토큰 만료 시간 추가, 헤더 바 새로고침 시 isLoggedIn 상태 확인 #137
  src/components/header/HeaderBar.test.tsx
  src/components/header/HeaderBar.tsx
  src/features/auth/utils/cookies.ts
Labels: ♻️ Refactor

#139 ✨ [Feat] 모임 만들기 react-date-picker 적용
  package-lock.json
  package.json
  src/app/bookclub/create/page.tsx
  src/features/club-create/components/DatePickerField.tsx
  src/features/club-create/components/index.ts
  src/features/club-create/hooks/useCreateBookClub.ts
  src/features/club-create/types/bookClubSchema.ts
  src/lib/utils/dateUtils.ts
Labels: 🎨 Design, ✨ Feature

#142 ✨ [Feature] 나의 모임 카드 구현
  src/components/card/my-club-card/MyClubCard.stories.tsx
  src/components/card/my-club-card/MyClubCard.tsx
  src/components/card/types/models.ts
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.test.tsx
  src/components/chip/Chip.tsx
  src/components/chip/club-chip/ClubChip.stories.tsx
  src/components/chip/club-chip/ClubChip.test.tsx
  src/components/chip/club-chip/ClubChip.tsx
  tailwind.config.ts
Labels: ♻️ Refactor, ✨ Feature

#144 ♻️[Refactor] 버튼 컴포넌트 리팩토링 #143
  src/app/layout.tsx
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/constants/button.ts
Labels: ♻️ Refactor, D-1

#146 💄[Design] 책 모임 메인페이지 UI 구현 #132
  package-lock.json
  src/app/bookclub/page.tsx
  src/app/layout.tsx
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/components/card/Card.tsx
  src/components/card/my-club-card/MyClubCard.stories.tsx
  src/components/card/my-club-card/MyClubCard.tsx
  src/components/card/types/models.ts
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.test.tsx
  src/components/chip/Chip.tsx
  src/components/chip/club-chip/ClubChip.stories.tsx
  src/components/chip/club-chip/ClubChip.test.tsx
  src/components/chip/club-chip/ClubChip.tsx
  src/components/drop-down/DropDown.tsx
  src/components/sorting-button/SortingButton.tsx
  src/constants/button.ts
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/components/FilterBar.tsx
  src/features/bookclub/components/Header.tsx
  src/features/bookclub/components/Main.tsx
  src/features/bookclub/components/index.ts
  tailwind.config.ts
Labels: 🎨 Design, 📱Mobile

#145 ✨[Feat] Modal 컴포넌트, 프로필 수정 / 리뷰 작성 모달 개발 #141
  public/icons/EditIcon.tsx
  src/components/button/Button.tsx
  src/components/modal/Modal.stories.tsx
  src/components/modal/Modal.test.tsx
  src/components/modal/Modal.tsx
  src/constants/avatar.ts
  src/features/profile/components/ProfileEditModal.tsx
  src/features/profile/components/WriteReviewModal.tsx
  src/features/profile/components/index.ts
Labels: 🎨 Design, ✅ Test, ✨ Feature

#150 [Merge] 모임 페이지 branch와 develop 병합 #72
  package-lock.json
  src/app/bookclub/page.tsx
  src/components/card/Card.tsx
  src/components/drop-down/DropDown.tsx
  src/components/sorting-button/SortingButton.tsx
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/components/FilterBar.tsx
  src/features/bookclub/components/Header.tsx
  src/features/bookclub/components/Main.tsx
  src/features/bookclub/components/index.ts
Labels: 🎨 Design

#149 ♻️[Refactor] 토큰 만료 시 유저 정보 초기화 #148
  src/store/authStore.ts
Labels: ♻️ Refactor

#152 💄[Design] 프로필 페이지 레이아웃 구현 #119
  package-lock.json
  src/app/profile/[userId]/page.tsx
  src/app/profile/page.tsx
  src/components/sorting-button/SortingButton.tsx
  src/components/tab/Tab.stories.tsx
  src/constants/tabs.ts
  src/features/profile/components/Header.tsx
  src/features/profile/components/MainContent.tsx
  src/features/profile/components/ProfilePage.tsx
  src/features/profile/components/clubs/ClubContents.tsx
  src/features/profile/components/clubs/HostedClubsList.tsx
  src/features/profile/components/clubs/JoinedClubList.tsx
  src/features/profile/components/clubs/MyReviewList.tsx
  src/features/profile/components/exchange/ExchangeContents.tsx
  src/features/profile/components/exchange/MyRegisteredBooks.tsx
  src/features/profile/components/exchange/TradeRecords.tsx
  src/features/profile/components/exchange/TradeReviews.tsx
  src/features/profile/components/profile/Profile.tsx
Labels: 🎨 Design, D-1

#156 ✨[Feat] WrittenReview를 활용한 ClubReview 컴포넌트 생성 #154
  src/app/layout.tsx
  src/components/header/HeaderBar.tsx
  src/components/written-review/WrittenReview.stories.tsx
  src/components/written-review/club-review/ClubReview.stories.tsx
  src/components/written-review/club-review/ClubReview.tsx
Labels: D-1, ✨ Feature

#151 ♻️ [Refactor] Card 리팩토링
  src/components/button/Button.tsx
  src/components/card/Card.stories.tsx
  src/components/card/Card.test.tsx
  src/components/card/Card.tsx
  src/components/card/ClubCard.stories.tsx
  src/components/card/full-card/FullCard.stories.tsx
  src/components/card/full-card/FullCard.tsx
  src/components/card/mock/mock.ts
  src/components/card/my-club-card/MyClubCard.stories.tsx
  src/components/card/my-club-card/MyClubCard.tsx
  src/components/card/simple-card/SimpleCard.stories.tsx
  src/components/card/simple-card/SimpleCard.tsx
  src/components/card/types/actions.ts
  src/components/card/types/base.ts
  src/components/card/types/card.ts
  src/components/card/types/clubCard.ts
  src/components/card/types/components.ts
  src/components/card/types/index.ts
  src/components/card/types/meeting.ts
  src/components/card/types/models.ts
  src/components/chip/club-chip/ClubChip.stories.tsx
  src/components/chip/club-chip/ClubChip.tsx
  src/features/bookclub/components/Main.tsx
  tailwind.config.ts
Labels: ♻️ Refactor, ✨ Feature

#166 💄[Design] 모임 상세 페이지 UI 구현 #147
  src/app/bookclub/[id]/page.tsx
  src/components/card/Card.tsx
  src/components/drop-down/DropDown.tsx
  src/features/club-details/api/index.ts
  src/features/club-details/components/BookClubDetailPage.tsx
  src/features/club-details/components/DescriptionSection.tsx
  src/features/club-details/components/HeaderSection.tsx
  src/features/club-details/components/ReviewListSection.tsx
  src/features/club-details/components/ReviewSummarySection.tsx
  src/features/club-details/components/index.ts
  src/features/club-details/container/index.ts
  src/features/club-details/hooks/index.ts
  src/features/club-details/types/index.ts
Labels: 🎨 Design

#167 ✨[Feat] 115 feature 모임 만들기 페이지 UI api 연동
  global.d.ts
  package-lock.json
  package.json
  src/app/bookclub/create/page.tsx
  src/app/layout.tsx
  src/features/club-create/api/index.ts
  src/features/club-create/components/index.ts
  src/features/club-create/container/CreateBookClubPage.tsx
  src/features/club-create/container/DatePickerField.tsx
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/container/ImageField.tsx
  src/features/club-create/container/RadioButtonGroup.tsx
  src/features/club-create/container/index.ts
  src/features/club-create/hooks/index.ts
  src/features/club-create/hooks/useBookClubForm.ts
  src/features/club-create/hooks/useCreateBookClub.ts
  src/features/club-create/hooks/useImageField.ts
  src/features/club-create/hooks/useSelectAddress.ts
  src/features/club-create/types/bookClubSchema.ts
  src/lib/utils/dateUtils.ts
Labels: D-0, ✨ Feature

#170 ✨ [Feature] 모임 만들기 페이지 디테일 수정
  src/features/club-create/components/InputField.tsx
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/container/ImageField.tsx
  src/features/club-create/container/RadioButtonGroup.tsx
  src/features/club-create/hooks/useImageField.ts
  src/features/club-create/types/bookClubSchema.ts
Labels: 🎨 Design, D-0, ✨ Feature

#164 ✨[Feat] feature page profile 프로필 컴포넌트 구현 #153
  public/icons/IcEdit.tsx
  public/icons/index.ts
  src/app/profile/page.tsx
  src/constants/avatar.ts
  src/features/profile/components/Header.tsx
  src/features/profile/components/ProfileEditModal.tsx
  src/features/profile/components/ProfileHeader.tsx
  src/features/profile/components/ProfilePage.tsx
  src/features/profile/components/profile/Profile.stories.tsx
  src/features/profile/components/profile/Profile.test.tsx
  src/features/profile/components/profile/Profile.tsx
  src/features/profile/types/index.ts
  src/features/profile/types/user.ts
Labels: 🎨 Design, D-1, ✨ Feature

#171 ✨ [Feature] 모임 만들기 페이지 구현
  global.d.ts
  package-lock.json
  package.json
  src/app/bookclub/create/page.tsx
  src/app/layout.tsx
  src/features/club-create/api/index.ts
  src/features/club-create/components/CreateClubFormField.tsx
  src/features/club-create/components/InputField.tsx
  src/features/club-create/components/index.ts
  src/features/club-create/container/CreateBookClubPage.tsx
  src/features/club-create/container/DatePickerField.tsx
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/container/ImageField.tsx
  src/features/club-create/container/RadioButtonGroup.tsx
  src/features/club-create/container/index.ts
  src/features/club-create/hooks/index.ts
  src/features/club-create/hooks/useBookClubForm.ts
  src/features/club-create/hooks/useCreateBookClub.ts
  src/features/club-create/hooks/useImageField.ts
  src/features/club-create/hooks/useSelectAddress.ts
  src/features/club-create/types/bookClubSchema.ts
  src/features/club-create/types/index.ts
  src/lib/utils/dateUtils.ts
Labels: D-0, ✨ Feature

#174 💄[Design] 반응형 디자인 수정 #173
  src/app/login/page.tsx
  src/features/auth/container/login-form/LoginForm.tsx
Labels: ♻️ Refactor, 🎨 Design

#177 ♻️ [Refactor] checkLoginStatus를 로그인 페이지에서 확인 #176
  src/components/header/HeaderBar.tsx
  src/features/auth/container/login-form/LoginForm.tsx
Labels: ♻️ Refactor

#181 ✨[Feat] 모임 메이페이지 이동 로직 추가 #180
  src/features/bookclub/components/ClubListSection.tsx
  src/features/bookclub/components/HeaderSection.tsx
Labels: ✨ Feature

#184 ♻️[Refactor] refactor 서비스 전반 코드 리팩토링
  src/features/bookclub/components/FilterSection.tsx
  src/features/club-details/components/HeaderSection.tsx
  src/features/profile/container/ClubContents.tsx
  src/features/profile/container/MainContent.tsx
  src/features/profile/container/ProfilePage.tsx
  src/middleware.ts
Labels: ♻️ Refactor, D-0

#186 ♻️ [Refactor] 중간 발표 이전 리팩토링
  public/images/defaultBookClub.jpg
  src/app/page.tsx
  src/components/header/HeaderBar.tsx
  src/constants/navigation.ts
  src/features/auth/hooks/useLoginSubmit.ts
  src/features/bookclub/components/ClubListSection.tsx
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/hooks/useBookClubForm.ts
  src/features/club-create/hooks/useCreateBookClub.ts
  src/features/club-create/hooks/usePopup.ts
  src/features/profile/components/clubs/JoinedClubList.tsx
Labels: ♻️ Refactor, D-0

#197 ♻️[Refactor] 모임 메인페이지 api 연동 #175
  src/app/bookclub/page.tsx
  src/app/page.tsx
  src/components/card/Card.tsx
  src/components/card/ClubCard.stories.tsx
  src/components/sorting-button/SortingButton.test.tsx
  src/components/sorting-button/SortingButton.tsx
  src/features/bookclub/api/bookclubApi.ts
  src/features/bookclub/api/index.ts
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/components/CategoryTabs.tsx
  src/features/bookclub/components/ClubListSection.tsx
  src/features/bookclub/components/FilterSection.tsx
  src/features/bookclub/components/SearchSection.tsx
  src/features/bookclub/components/index.ts
  src/features/bookclub/container/BookClubContainer.tsx
  src/features/bookclub/hooks/useFetchBookClubList.ts
  src/features/bookclub/types/bookclubs.ts
  src/features/bookclub/types/index.ts
  src/lib/utils/formatDateForUI.ts
Labels: ✨ Feature

#200 ✨ [Feature] page-profile 나의 리뷰 UI 구현 #196
  src/components/written-review/WrittenReview.stories.tsx
  src/components/written-review/WrittenReview.tsx
  src/components/written-review/types/writtenReview.ts
  src/features/profile/components/clubs/MyReviewList.tsx
  src/features/profile/types/index.ts
  src/features/profile/types/user.ts
  src/lib/utils/dateUtils.ts
Labels: 🎨 Design, D-1

#202 ✨ [Feature] tanstack-query 전역 설정 및 쿼리키 팩토리 추가
  package-lock.json
  package.json
  src/features/club-create/hooks/useCreateBookClub.ts
  src/features/react-query/book-club/customHooks.ts
  src/features/react-query/book-club/index.ts
  src/features/react-query/book-club/queries.ts
  src/lib/utils/reactQueryProvider.tsx
Labels: D-1, ✨ Feature

#212 ✨ [Feat] 뱃지 컴포넌트 구현
  src/components/badge/Badge.stories.tsx
  src/components/badge/Badge.test.tsx
  src/components/badge/Badge.tsx
Labels: ✅ Test, ✨ Feature

#209 💄[Design] profile 페이지 UI 구현
  src/components/card/Card.tsx
  src/components/card/types/clubCard.ts
  src/components/written-review/WrittenReview.stories.tsx
  src/components/written-review/WrittenReview.tsx
  src/components/written-review/types/writtenReview.ts
  src/features/profile/components/clubs/HostedClubsList.tsx
  src/features/profile/components/clubs/JoinedClubList.tsx
  src/features/profile/components/clubs/MyReviewList.tsx
  src/features/profile/constants/meassage.ts
  src/features/profile/constants/temp.ts
  src/features/profile/types/index.ts
  src/features/profile/types/user.ts
  src/lib/utils/dateUtils.ts
Labels: 🎨 Design, D-2

#213 ✨ [Feat] 모임 만들기 페이지 입력 필드 추가 및 디자인 수정
  public/icons/CameraIcon.tsx
  public/icons/ImageIcon.tsx
  public/icons/index.ts
  src/features/club-create/api/index.ts
  src/features/club-create/components/CreateClubFormField.tsx
  src/features/club-create/container/DatePickerField.tsx
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/container/ImageField.tsx
  src/features/club-create/container/RadioButtonGroup.tsx
  src/features/club-create/container/datepicker.css
  src/features/club-create/hooks/useImageField.ts
  src/features/club-create/hooks/useSelectAddress.ts
  src/features/club-create/types/bookClubSchema.ts
Labels: ♻️ Refactor, ✨ Feature

#216 ✅ [Test] 채팅 카드 컴포넌트 테스트 코드 작성
  src/components/chat-card/ChatCard.test.tsx
  src/components/chat-card/ChatCard.tsx
Labels: ✅ Test

#218 ✨ [Feat] 채팅 카드 컴포넌트 만들기
  public/icons/LocationIcon.tsx
  public/icons/OnlineIcon.tsx
  public/icons/index.ts
  src/components/badge/Badge.stories.tsx
  src/components/badge/Badge.test.tsx
  src/components/badge/Badge.tsx
  src/components/chat-card/ChatCard.stories.tsx
  src/components/chat-card/ChatCard.test.tsx
  src/components/chat-card/ChatCard.tsx
  src/components/chat-card/VariantChatCard.stories.tsx
  src/components/chat-card/types/chatCard.ts
  src/components/chat-card/types/index.ts
  src/components/chat-card/types/variantChatCard.ts
  src/components/participant-counter/ParticipantCounter.test.tsx
  src/components/participant-counter/ParticipantCounter.tsx
Labels: ♻️ Refactor, ✅ Test, ✨ Feature

#199 ✨[Feat] accessToken 만료 되었을 때 refresh #188
  package-lock.json
  package.json
  src/app/actions.ts
  src/app/layout.tsx
  src/components/toast/toast.tsx
  src/features/auth/api/auth.ts
  src/features/auth/hooks/useLoginSubmit.ts
  src/lib/utils/apiClient.ts
  src/middleware.ts
Labels: ✨ Feature

#217 ✨[Feat] msw 세팅 #201
  jest.config.js
  next.config.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/app/instrumentation.ts
  src/app/layout.tsx
  src/components/MSWComponent.tsx
  src/mocks/browsers.ts
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
Labels: ✨ Feature

#219 ♻️[Refactor] 모임 메인페이지 코드 구조 개선 #204
  src/app/bookclub/page.tsx
  src/app/page.tsx
  src/components/common-layout/CategoryTabs.tsx
  src/components/common-layout/EmptyState.tsx
  src/components/common-layout/FilterBar.tsx
  src/components/common-layout/FilterSection.tsx
  src/components/common-layout/SearchSection.tsx
  src/components/common-layout/index.ts
  src/features/auth/types/user.ts
  src/features/bookclub/api/bookclubApi.ts
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/components/ClubListSection.tsx
  src/features/bookclub/components/FilterSection.tsx
  src/features/bookclub/components/HeaderSection.tsx
  src/features/bookclub/components/index.ts
  src/features/bookclub/container/BookClubContainer.tsx
  src/features/bookclub/hooks/useFetchBookClubList.ts
  src/features/react-query/book-club/queries.ts
  src/lib/utils/clubUtils.ts
  src/lib/utils/filterUtils.ts
  src/lib/utils/formatDateForUI.ts
  src/types/bookclubs.ts
Labels: ♻️ Refactor

#222 🐛 [Bug] msw 적용 후 Npm install시 보안 경고
  package-lock.json
Labels: 🐛 Bug, D-0

#226 🐛 [Fix] 레이아웃 수정
  src/app/layout.tsx
Labels: 🐛 Bug, D-0

#230 ✨ [Feat] 채팅 말풍선 컴포넌트 구현
  src/components/avatar/Avatar.tsx
  src/components/chat-container/chat-bubble/ChatBubble.stories.tsx
  src/components/chat-container/chat-bubble/ChatBubble.test.tsx
  src/components/chat-container/chat-bubble/ChatBubble.tsx
  src/components/chat-container/chat-bubble/VariantChatBubble.stories.tsx
  src/components/chat-container/chat-bubble/types/chatBubble.ts
  src/components/chat-container/chat-bubble/types/index.ts
  src/components/chat-container/chat-bubble/types/variantChatBubble.ts
  src/constants/avatar.ts
Labels: ✅ Test, ✨ Feature

#232 💄[Design] 채팅 페이지 UI 개발 #231
  src/app/chat/page.tsx
  src/constants/navigation.ts
  src/features/chat/components/chat-header/ChatHeader.tsx
  src/features/chat/container/BookClubChatContainer.tsx
  src/features/chat/container/ChatContainer.tsx
  src/features/chat/container/ExchangeChatContainer.tsx
  src/middleware.ts
Labels: 🎨 Design

#229 ✨[Feat] 프로필 페이지 나의 모임 api 연동
  src/api/auth/authClientAPI.ts
  src/api/auth/authServerAPI.ts
  src/api/book-club/bookClubLikeAPI.ts
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/bookClubMemberAPI.ts
  src/api/book-club/bookClubReviewAPI.ts
  src/api/book-club/index.ts
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/index.ts
  src/api/book-club/react-query/queries.ts
  src/api/book-club/types.ts
  src/api/chat/index.ts
  src/api/user/react-query/queries.ts
  src/components/card/Card.tsx
  src/components/card/types/clubCard.ts
  src/components/filter-checkbox/FilterCheckbox.test.tsx
  src/components/pop-up-button/PopUpButton.tsx
  src/components/pop-up/PopUp.tsx
  src/components/sorting-button/SortingButton.test.tsx
  src/components/sorting-button/SortingButton.tsx
  src/components/tab/Tab.stories.tsx
  src/constants/tabs.ts
  src/features/club-create/hooks/useCreateBookClub.ts
  src/features/profile/api/index.ts
  src/features/profile/api/myJoinedApi.ts
  src/features/profile/components/clubs/HostedClubsList.tsx
  src/features/profile/components/clubs/JoinedClubList.tsx
  src/features/profile/components/clubs/MyReviewList.tsx
  src/features/profile/components/profile/Profile.tsx
  src/features/profile/constants/temp.ts
  src/features/profile/container/ClubContents.tsx
  src/features/profile/hooks/useFetchMyJoinedList.ts
  src/features/profile/types/index.ts
  src/features/react-query/book-club/customHooks.ts
  src/middleware.ts
Labels: D-1, ✨ Feature

#234 ✨[Feat] 프로필 수정하기 api 연동
  src/api/auth/authClientAPI.ts
  src/api/auth/react-query/customHooks.ts
  src/api/auth/react-query/index.ts
  src/api/auth/react-query/queries.ts
  src/api/auth/types.ts
  src/features/profile/api/myJoinedApi.ts
  src/features/profile/components/ProfileHeader.tsx
  src/features/profile/components/info/Info.stories.tsx
  src/features/profile/components/info/Info.test.tsx
  src/features/profile/components/info/Info.tsx
  src/features/profile/components/info/InfoEditModal.tsx
  src/features/profile/components/info/index.ts
  src/features/profile/components/profile/index.ts
  src/features/profile/container/ProfileHeader.tsx
  src/features/profile/container/index.ts
  src/features/profile/hooks/useFetchMyJoinedList.ts
  src/features/profile/types/index.ts
  src/features/react-query/book-club/customHooks.ts
  src/types/Info.ts
  src/types/review.ts
Labels: D-1, ✨ Feature

#233 ✨ [Feat] 채팅 리스트 구현
  package.json
  src/components/avatar/Avatar.tsx
  src/constants/avatar.ts
  src/features/chat-room/components/chat-bubble/ChatBubble.stories.tsx
  src/features/chat-room/components/chat-bubble/ChatBubble.test.tsx
  src/features/chat-room/components/chat-bubble/ChatBubble.tsx
  src/features/chat-room/components/chat-bubble/components/MeBubble.tsx
  src/features/chat-room/components/chat-bubble/components/OpponentBubble.tsx
  src/features/chat-room/components/chat-bubble/components/SystemBubble.tsx
  src/features/chat-room/components/chat-bubble/components/atoms/atoms.stories.tsx
  src/features/chat-room/components/chat-bubble/components/atoms/atoms.tsx
  src/features/chat-room/container/chat-bubble-list/ChatBubbleList.stories.tsx
  src/features/chat-room/container/chat-bubble-list/ChatBubbleList.tsx
  src/features/chat-room/container/chat-bubble-list/components/ChatMessage.tsx
  src/features/chat-room/container/chat-bubble-list/components/SystemMessage.tsx
  src/features/chat-room/hooks/useMessageRenderer.ts
  src/features/chat-room/types/chatBubbleList.ts
  src/features/chat/components/chat-card/ChatCard.stories.tsx
  src/features/chat/components/chat-card/ChatCard.test.tsx
  src/features/chat/components/chat-card/ChatCard.tsx
  src/features/chat/components/chat-card/VariantChatCard.stories.tsx
  src/features/chat/components/chat-card/types/chatCard.ts
  src/features/chat/components/chat-card/types/index.ts
  src/features/chat/components/chat-card/types/variantChatCard.ts
  src/features/chat/container/BookClubChatContainer.tsx
Labels: ♻️ Refactor, ✨ Feature

#240 ✨[Feat] 프로필 페이지 내가 만든 모임 api 연동 #236
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/queries.ts
  src/components/card/Card.tsx
  src/components/card/types/clubCard.ts
  src/features/profile/components/clubs/HostedClubsList.tsx
  src/features/profile/container/ClubContents.tsx
  src/features/profile/types/index.ts
  src/types/bookclubs.ts
Labels: D-1, ✨ Feature

#246 ✨[Feat] 프로필 페이지 나의 리뷰 api 연동 #237
  src/constants/tabs.ts
  src/features/profile/components/ProfileHeader.tsx
  src/features/profile/components/clubs/index.ts
  src/features/profile/constants/meassage.ts
  src/features/profile/constants/mock.ts
  src/features/profile/container/ClubContents.tsx
  src/features/profile/container/CreatedClubsList.tsx
  src/features/profile/container/JoinedClubList.tsx
  src/features/profile/container/MainContent.tsx
  src/features/profile/container/MyReviewList.tsx
  src/features/profile/container/ProfilePage.tsx
  src/features/profile/container/index.ts
  src/lib/hooks/useCancelClub.ts
Labels: ♻️ Refactor, D-1, ✨ Feature

#252 ✨[Feat] 프로필 페이지 api 연동 #205
  src/api/auth/authClientAPI.ts
  src/api/auth/react-query/customHooks.ts
  src/api/auth/react-query/index.ts
  src/api/auth/react-query/queries.ts
  src/api/auth/types.ts
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/queries.ts
  src/components/card/Card.tsx
  src/components/card/types/clubCard.ts
  src/constants/tabs.ts
  src/features/profile/api/myJoinedApi.ts
  src/features/profile/components/ProfileHeader.tsx
  src/features/profile/components/clubs/HostedClubsList.tsx
  src/features/profile/components/clubs/index.ts
  src/features/profile/components/info/Info.stories.tsx
  src/features/profile/components/info/Info.test.tsx
  src/features/profile/components/info/Info.tsx
  src/features/profile/components/info/InfoEditModal.tsx
  src/features/profile/components/info/index.ts
  src/features/profile/components/profile/index.ts
  src/features/profile/constants/meassage.ts
  src/features/profile/constants/mock.ts
  src/features/profile/container/ClubContents.tsx
  src/features/profile/container/CreatedClubsList.tsx
  src/features/profile/container/JoinedClubList.tsx
  src/features/profile/container/MainContent.tsx
  src/features/profile/container/MyReviewList.tsx
  src/features/profile/container/ProfileHeader.tsx
  src/features/profile/container/ProfilePage.tsx
  src/features/profile/container/index.ts
  src/features/profile/hooks/useFetchMyJoinedList.ts
  src/features/profile/types/index.ts
  src/features/react-query/book-club/customHooks.ts
  src/lib/hooks/useCancelClub.ts
  src/types/Info.ts
  src/types/bookclubs.ts
  src/types/review.ts
Labels: D-1, ✨ Feature

#249 💄[Design] 폰트 적용
  public/fonts/Pretendard-1.3.8/LICENSE.txt
  public/fonts/Pretendard-1.3.8/web/static/pretendard-subset.css
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-Black.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-Bold.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-ExtraBold.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-ExtraLight.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-Light.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-Medium.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-Regular.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-SemiBold.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff-subset/Pretendard-Thin.subset.woff
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-Black.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-Bold.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-ExtraBold.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-ExtraLight.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-Light.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-Medium.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-Regular.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-SemiBold.subset.woff2
  public/fonts/Pretendard-1.3.8/web/static/woff2-subset/Pretendard-Thin.subset.woff2
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 Design

#250 ✨ [Feat] 로딩 컴포넌트 구현
  public/assets/Spinner.gif
  public/svg/index.ts
  src/components/loading/Loading.stories.tsx
  src/components/loading/Loading.test.tsx
  src/components/loading/Loading.tsx
Labels: ✨ Feature

#235 ✨[Feat] 찜 목록 페이지 UI 생성 #157
  public/icons/IcCheckOnly.tsx
  public/icons/index.ts
  src/app/bookclub/page.tsx
  src/app/page.tsx
  src/app/wish/page.tsx
  src/components/common-layout/HeaderSection.tsx
  src/components/common-layout/index.ts
  src/components/filter-checkbox/FilterCheckbox.tsx
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/components/HeaderSection.tsx
  src/features/bookclub/components/index.ts
  src/features/club-wish/components/ClubWishList.tsx
  src/features/club-wish/components/WishPage.tsx
  src/features/club-wish/mocks/wishPageMockData.ts
Labels: ✨ Feature

#256 ✨[Feat] 모임 참여하기 api 연결 #228
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/bookClubMemberAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/components/card/Card.tsx
  src/components/card/ClubCard.stories.tsx
  src/components/card/types/clubCard.ts
  src/components/pop-up/PopUp.tsx
  src/features/club-details/components/HeaderSection.tsx
  src/mocks/browsers.ts
  src/mocks/handlers/bookclub/getBookclubsHandler.ts
  src/mocks/handlers/bookclub/getClubDetailHandler.ts
  src/mocks/handlers/handlers.ts
  src/mocks/server.ts
Labels: ✨ Feature

#254 ♻️ [Refactor] 검색창 Input 리팩토링
  public/icons/PencilIcon.tsx
  public/icons/index.ts
  src/components/common-layout/SearchSection.tsx
  src/components/input/Input.stories.tsx
  src/components/input/Input.test.tsx
  src/components/input/Input.tsx
  src/components/input/message-input/MessageInput.stories.tsx
  src/components/input/message-input/MessageInput.tsx
  src/components/input/search-input/SearchInput.stories.tsx
  src/components/input/search-input/SearchInput.tsx
  src/components/search-box/SearchBox.test.tsx
  src/components/search-box/SearchBox.tsx
Labels: ♻️ Refactor, ✨ Feature

#257 ✨ [Feat] 아이콘 버튼 컴포넌트 구현
  public/icons/MessageIcon.tsx
  public/icons/index.ts
  src/components/icon-button/IconButton.stories.tsx
  src/components/icon-button/IconButton.test.tsx
  src/components/icon-button/IconButton.tsx
  src/features/profile/components/info/Info.tsx
  tailwind.config.ts
Labels: ✨ Feature

#251 🐛[Fix] bug dropdown 버튼 버그 수정 #238
  src/components/common-layout/FilterSection.tsx
  src/components/drop-down/DropDown.test.tsx
  src/components/drop-down/DropDown.tsx
  src/components/header/HeaderBar.test.tsx
  src/constants/dropdown.ts
Labels: 🐛 Bug, 🎨 Design, D-1

#258 ✨ [Feat] 카드 모임 '온라인' 인경우 장소대신 온라인 텍스트 추가
  src/components/card/Card.stories.tsx
  src/components/card/Card.tsx
  src/components/card/types/card.ts
  src/features/club-create/container/RadioButtonGroup.tsx
Labels: ✨ Feature
