Repository codeit-team3/FE, pull requests merged in 2025-01, with the labels that each got.

#266 ✨[Feat] 모임 상세 페이지 찜 및 리뷰 api 연동 #227
  src/api/book-club/bookClubLikeAPI.ts
  src/api/book-club/bookClubReviewAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/queries.ts
  src/api/book-club/types.ts
  src/components/common-layout/EmptyState.tsx
  src/features/bookclub/components/ClubListSection.tsx
  src/features/club-details/components/BookClubDetailPage.tsx
  src/features/club-details/components/DescriptionSection.tsx
  src/features/club-details/components/HeaderSection.tsx
  src/features/club-details/components/ReviewList.tsx
  src/features/club-details/components/ReviewListSection.tsx
  src/features/club-details/components/ReviewSection.tsx
  src/features/club-details/components/ReviewSummary.tsx
  src/features/club-details/components/index.ts
  src/features/club-details/hooks/index.ts
  src/features/club-details/hooks/useClubDetails.ts
  src/features/club-details/hooks/useJoinClub.ts
  src/features/club-details/mocks/DetailReviewDatas.ts
  src/features/club-details/types/index.ts
  src/lib/hooks/index.ts
  src/lib/hooks/useLeaveClub.ts
  src/lib/hooks/useLikeClub.ts
  src/lib/hooks/useLikeWithAuthCheck.ts
  src/lib/hooks/useUnLikeClub.ts
  src/types/review.ts
Labels: ✨ Feature

#262 ✨ [Feat] 모임 만들기 추가 기능 및 구조 변경
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/app/bookclub/create/page.tsx
  src/features/club-create/container/CreateBookClubPage.tsx
  src/features/club-create/container/DatePickerField.tsx
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/container/ImageField.tsx
  src/features/club-create/container/RadioButtonGroup.tsx
  src/features/club-create/container/index.ts
  src/features/club-create/hooks/useBookClubForm.ts
  src/features/club-create/hooks/useCreateBookClub.ts
  src/features/club-create/hooks/useSelectAddress.ts
  src/features/club-create/types/bookClubSchema.ts
  src/features/club-create/utils/bookClubFormUtils.tsx
  src/features/react-query/book-club/customHooks.ts
  src/styles/datepicker.css
Labels: ♻️ Refactor, ✨ Feature

#263 ✨[Feat] 타 유저 프로필페이지 api 연동 #259
  next.config.ts
  src/api/auth/authClientAPI.ts
  src/api/auth/react-query/customHooks.ts
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/queries.ts
  src/api/user/react-query/queries.ts
  src/app/profile/[userId]/page.tsx
  src/app/profile/page.tsx
  src/features/profile/components/info/Info.test.tsx
  src/features/profile/components/info/Info.tsx
  src/features/profile/components/info/InfoEditModal.tsx
  src/features/profile/container/ClubContents.tsx
  src/features/profile/container/CreatedClubList.tsx
  src/features/profile/container/JoinedClubList.tsx
  src/features/profile/container/MainContent.tsx
  src/features/profile/container/MyCreatedClubList.tsx
  src/features/profile/container/MyJoinedClubList.tsx
  src/features/profile/container/MyWrittenReviewList.tsx
  src/features/profile/container/ProfileHeader.tsx
  src/features/profile/container/ProfilePage.tsx
  src/features/profile/container/WrittenReviewList.tsx
  src/features/profile/types/index.ts
  src/lib/hooks/useGetUserByPath.ts
  src/types/Info.ts
  src/types/bookclubs.ts
Labels: ✨ Feature

#271 💄[Design] 프로필 페이지 및 탭 컴포넌트 UI 리팩토링 #265
  src/api/book-club/react-query/queries.ts
  src/app/exchange/page.tsx
  src/app/layout.tsx
  src/components/button/Button.tsx
  src/components/tab/Tab.stories.tsx
  src/components/tab/Tab.tsx
  src/components/written-review/types/writtenReview.ts
  src/constants/button.ts
  src/constants/tabs.ts
  src/features/chat/container/ChatContainer.tsx
  src/features/chat/container/ExchangeChatContainer.tsx
  src/features/exchange/container/ExchangeMainSection.tsx
  src/features/exchange/container/ExchangePage.tsx
  src/features/profile/components/clubs/ProfileWrittenReview.tsx
  src/features/profile/components/exchange/ExchangeContents.tsx
  src/features/profile/components/exchange/MyRegisteredBooks.tsx
  src/features/profile/components/exchange/TradeRecords.tsx
  src/features/profile/components/exchange/TradeReviews.tsx
  src/features/profile/components/info/Info.test.tsx
  src/features/profile/components/info/Info.tsx
  src/features/profile/constants/meassage.ts
  src/features/profile/container/ClubContents.tsx
  src/features/profile/container/CreatedClubList.tsx
  src/features/profile/container/JoinedClubList.tsx
  src/features/profile/container/MainContent.tsx
  src/features/profile/container/MyCreatedClubList.tsx
  src/features/profile/container/MyJoinedClubList.tsx
  src/features/profile/container/MyWrittenReviewList.tsx
  src/features/profile/container/ProfileHeader.tsx
  src/features/profile/container/WrittenReviewList.tsx
  src/features/profile/types/index.ts
Labels: 🎨 Design

#275 ✨[Feat] 모임 상세 평점별 리뷰 개수 구현
  src/components/rating-display/RatingDisplay.tsx
  src/features/club-details/components/DescriptionSection.tsx
  src/features/club-details/components/HeaderSection.tsx
  src/features/club-details/components/ReviewList.tsx
  src/features/club-details/components/ReviewSummary.tsx
  src/features/club-details/types/index.ts
  src/mocks/mockDatas.ts
  src/types/bookclubs.ts
Labels: 🎨 Design, ✨ Feature

#272 ✨[Feat] 모임 메인 페이지 필터링 및 찜하기 구현 #264
  src/api/book-club/bookClubMainAPI.ts
  src/components/common-layout/FilterBar.tsx
  src/components/common-layout/FilterSection.tsx
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/components/ClubListSection.tsx
  src/features/bookclub/hooks/useFetchBookClubList.ts
  src/features/club-wish/components/WishPage.tsx
  src/lib/utils/filterUtils.ts
  src/types/bookclubs.ts
Labels: ✨ Feature

#274 ✨ [Feat] tanstack-query 및 쿼리키 설정 변경
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/bookClubReviewAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/queries.ts
  src/api/book-club/types.ts
  src/features/auth/api/auth.ts
  src/features/bookclub/components/ClubListSection.tsx
  src/features/bookclub/hooks/useFetchBookClubList.ts
  src/features/club-details/components/ReviewList.tsx
  src/features/club-details/hooks/useClubDetails.ts
  src/features/profile/container/CreatedClubList.tsx
  src/features/profile/container/JoinedClubList.tsx
  src/features/profile/container/MyCreatedClubList.tsx
  src/features/profile/container/MyJoinedClubList.tsx
  src/features/profile/container/MyWrittenReviewList.tsx
  src/features/profile/container/WrittenReviewList.tsx
  src/lib/utils/filterUtils.ts
  src/lib/utils/reactQueryProvider.tsx
  src/middleware.ts
  src/types/bookclubs.ts
Labels: ♻️ Refactor, ✨ Feature

#281 ♻️ [Refactor] 상세조회 페이지 리뷰 리스트 프로그레스바 수정
  src/features/club-details/components/ReviewSummary.tsx
  src/features/club-details/utils/rating.ts
Labels: ♻️ Refactor

#282 ✨ [Feat] 모임 만들기 모집 마감 날짜 -> 만나는 날 이전으로만 선택 가능하도록 구현
  src/api/book-club/react-query/customHooks.ts
  src/features/club-create/container/DatePickerField.tsx
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/hooks/useBookClubForm.ts
  src/features/club-create/types/bookClubSchema.ts
Labels: D-0, ✨ Feature

#284 ♻️[Refactor] 채팅 리펙토링 #283
  src/app/chat/[id]/page.tsx
  src/features/auth/api/auth.ts
  src/features/auth/api/refreshAccessToken.ts
  src/lib/utils/apiClient.ts
  src/middleware.ts
Labels: ♻️ Refactor, 🎨 Design

#286 ✨[Feat] 모임 상세 누락 정보 추가 및 UI 수정 #227
  src/components/card/Card.tsx
  src/components/card/ClubCard.stories.tsx
  src/components/card/types/clubCard.ts
  src/components/common-layout/FilterSection.tsx
  src/components/written-review/WrittenReview.tsx
  src/components/written-review/club-review/ClubReview.stories.tsx
  src/components/written-review/club-review/ClubReview.tsx
  src/components/written-review/types/writtenReview.ts
  src/features/club-details/components/DescriptionSection.tsx
  src/features/club-details/components/HeaderSection.tsx
  src/features/club-details/components/ReviewList.tsx
  src/features/club-details/mocks/DetailReviewDatas.ts
  src/features/club-wish/components/ClubWishList.tsx
  src/types/review.ts
Labels: 🎨 Design, ✨ Feature

#293 ✨[Feat] api 수정 및 추가 사항 적용
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/likeOptimisticUpdate.ts
  src/components/common-layout/FilterBar.tsx
  src/components/common-layout/FilterSection.tsx
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/hooks/useFetchBookClubList.ts
  src/features/club-details/components/ReviewSummary.tsx
  src/features/club-wish/components/WishPage.tsx
  src/lib/constants/filters.ts
  src/types/bookclubs.ts
Labels: 🎨 Design, ✨ Feature

#294 🐛 [Bug] 찜하기 동작 에러
  src/api/book-club/bookClubMainAPI.ts
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/likeOptimisticUpdate.ts
Labels: 🐛 Bug, D-0

#307 ♻️[Refactor] 채팅창 높이 지정 #305
  src/app/chat/[id]/page.tsx
Labels: ♻️ Refactor, 🎨 Design

#311 ♻️[Refactor] 토스트가 사라지지 않는 버그 수정
  src/app/layout.tsx
  src/components/header/HeaderBar.tsx
  src/components/toast/toast.tsx
  src/features/auth/api/auth.ts
Labels: 🐛 Bug, ♻️ Refactor

#314 ♻️[Refactor] 토스트 메시지 상수로 관리
  src/api/auth/react-query/customHooks.ts
  src/api/book-club/react-query/customHooks.ts
  src/constants/messages/toast.ts
  src/features/club-details/hooks/useJoinClub.ts
  src/features/profile/container/MyJoinedClubList.tsx
  src/lib/hooks/useCancelClub.ts
  src/lib/hooks/useLeaveClub.ts
  src/lib/hooks/useLikeClub.ts
  src/lib/hooks/useUnLikeClub.ts
Labels: ♻️ Refactor

#313 ♻️ [Refactor] 프로그레스바 넘침 현상 해결
  src/components/progress-bar/ProgressBar.test.tsx
  src/components/progress-bar/ProgressBar.tsx
Labels: ♻️ Refactor

#319 📝[Docs] 리드미 포맷 적용
  README.md
Labels: 📝 Docs

#318 ✅[Test] 로그인 테스트 코드 추가
  src/features/auth/container/login-form/LoginForm.test.tsx
Labels: ✅ Test
