Repository codeit-team3/FE, pull requests merged in 2025-02, with the labels that each got.

#334 🐛[Fix] ChatBubbleList storybook router 에러 fix
  src/features/chat-room/container/chat-bubble-list/ChatBubbleList.stories.tsx
Labels: 🐛 Bug

#327 [Test] 모임 만들기 페이지 단위 테스트 코드 작성
  jest.config.js
  src/features/club-create/container/FormContainer.tsx
  src/features/club-create/container/ImageField/ImageField.test.tsx
  src/features/club-create/container/ImageField/ImageField.tsx
  src/features/club-create/container/RadioButtonGroup/RadioButtonGroup.test.tsx
  src/features/club-create/container/RadioButtonGroup/RadioButtonGroup.tsx
Labels: ✅ Test

#321 ✨ [Feature] 에러 전역 처리
  public/icons/AlertCircleIcon.tsx
  public/icons/index.ts
  public/images/errorImage.png
  src/app/bookclub/create/error.tsx
  src/app/global-error.tsx
  src/app/not-found.tsx
  src/components/error/ErrorBoundary.tsx
  src/components/error/ErrorFallback.tsx
  src/components/error/ErrorHandlingWrapper.tsx
  src/components/error/ErrorTemplate.tsx
  src/features/profile/components/info/Info.test.tsx
  src/features/profile/container/ClubContents.tsx
  src/lib/hooks/useGetUserByPath.ts
  src/lib/utils/reactQueryProvider.tsx
Labels: ✨ Feature

#322 ✨[Feat] 모임 찾기 검색 debounce 적용
  package-lock.json
  package.json
  src/components/common-layout/FilterBar.tsx
  src/components/input/search-input/SearchInput.tsx
  src/features/chat-room/container/chat-bubble-list/ChatBubbleList.tsx
Labels: ♻️ Refactor, ✨ Feature

#324 💄[Design] 모임 카드, 버튼 호버 효과 적용
  src/components/card/Card.tsx
Labels: 🎨 Design

#326 💄[Design] 모임 찾기 메인 페이지 하단 패딩 추가
  src/features/bookclub/components/BookClubMainPage.tsx
Labels: 🎨 Design

#335 ♻️[Refactor] 찜하기 구현 작업
  src/api/book-club/react-query/customHooks.ts
  src/api/book-club/react-query/likeOptimisticUpdate.ts
  src/app/bookclub/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/card/Card.tsx
  src/components/card/types/card.ts
  src/components/card/types/clubCard.ts
  src/constants/filters.ts
  src/features/bookclub/components/BookClubMainPage.tsx
  src/features/bookclub/components/ClubListSection.tsx
  src/features/bookclub/hooks/useFetchBookClubList.test.tsx
  src/features/bookclub/hooks/useFetchBookClubList.ts
  src/features/club-details/components/HeaderSection.tsx
  src/features/club-find/api/index.ts
  src/features/club-find/components/index.ts
  src/features/club-find/container/index.ts
  src/features/club-find/hooks/index.ts
  src/features/club-find/types/index.ts
  src/lib/contexts/LikeContext.tsx
  src/lib/hooks/useLikeClub.ts
  src/lib/hooks/useLikeWithAuthCheck.ts
  src/lib/hooks/useUnLikeClub.ts
  src/lib/utils/fetchBookClub.test.ts
  src/lib/utils/fetchBookClubs.ts
  src/lib/utils/getServerSideToken.ts
Labels: ♻️ Refactor, 🎨 Design

#337 ✨[Feat] 모임 찾기 페이지 비로그인 찜 클릭 시 로그인 안내창 추가 #336
  src/features/bookclub/components/ClubListSection.tsx
  src/features/club-details/components/HeaderSection.tsx
  src/lib/hooks/useLikeWithAuthCheck.ts
Labels: ✨ Feature
